feat(security-apps): add Open Policy Agent
adfinis-sygroup/helm-charts pull request #122
Opened 2020-11-24 17:44 UTC by hairmare

2020-11-24 18:28 UTC, eyenx requested changes

2020-11-24 18:28 UTC, eyenx commented on charts/security-apps/examples/opa.yaml
> +falco:
```
opa:
```

2020-11-24 18:28 UTC, eyenx commented on charts/security-apps/README.md
> +| opa.repoURL | string | [repo](https://charts.helm.sh/stable) | Repo URL |
Is there really no official chart in https://github.com/open-policy-agent ?

Or can not this be done with gatekeeper?

2020-11-24 19:30 UTC, tongpu commented
I guess we should rather be using gatekeeper: https://github.com/open-policy-agent/gatekeeper#deploying-via-helm
And before we do that we should figure out rego. ;)

2020-11-25 12:03 UTC, hairmare commented
This should indeed be gatekeeper and not stable/opa I'll make a new pr with gatekeeper.

2020-11-25 12:03 UTC, closed without merging