chore(sscd): update to 1.1.*
adfinis-sygroup/helm-charts pull request #550
Opened 2022-02-04 12:20 UTC by eyenx

# Description

Updates to latest version 1.1.0

# Changes

* feat: add token requests client 
* feat: send NodePublishVolumeRequest.VolumeContext in MountRequest to provider
* security: fix CVE-2021-3995, CVE-2021-3996
* security: fix CVE-2021-43618

# Checklist

* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

---
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

2022-02-04 12:23 UTC, hairmare commented
Please update you description to include some links and more details on the changes + maybe section on any needed steps during the upgrade.

2022-02-04 12:27 UTC, vmaillot approved these changes

2022-02-04 12:27 UTC, eyenx commented
We wait until 1.1.0 is relased as chart.

2022-02-14 08:58 UTC, hairmare requested changes
reviewing so it won't pop up in mattermost: please add an elaborate description containg links to upstreams changeset.

2022-02-15 06:57 UTC, closed without merging